import 'tourist_spot.dart';
import 'hotel.dart';
import 'restaurant.dart';

class MockGujaratData {
  static final List<TouristSpot> spots = [
    TouristSpot(
      id: 'spot_1',
      name: 'Statue of Unity',
      category: 'Monument',
      latitude: 21.8380,
      longitude: 73.7191,
      entryFee: 150.0,
      distanceKm: 0.0,
      estimatedVisitDuration: const Duration(hours: 3),
      rating: 4.8,
      openingTime: '08:00 AM',
      closingTime: '06:00 PM',
    ),
    TouristSpot(
      id: 'spot_2',
      name: 'Sabarmati Ashram',
      category: 'Heritage',
      latitude: 23.0602,
      longitude: 72.5808,
      entryFee: 0.0,
      distanceKm: 5.0,
      estimatedVisitDuration: const Duration(hours: 2),
      rating: 4.7,
      openingTime: '08:30 AM',
      closingTime: '06:30 PM',
    ),
    TouristSpot(
      id: 'spot_3',
      name: 'Gir National Park',
      category: 'Wildlife',
      latitude: 21.1243,
      longitude: 70.8242,
      entryFee: 800.0,
      distanceKm: 350.0,
      estimatedVisitDuration: const Duration(hours: 4),
      rating: 4.6,
      openingTime: '06:00 AM',
      closingTime: '05:00 PM',
    ),
    TouristSpot(
      id: 'spot_4',
      name: 'White Rann of Kutch',
      category: 'Nature',
      latitude: 23.8293,
      longitude: 69.5312,
      entryFee: 100.0,
      distanceKm: 400.0,
      estimatedVisitDuration: const Duration(hours: 3),
      rating: 4.9,
      openingTime: '06:00 AM',
      closingTime: '08:00 PM',
    ),
    TouristSpot(
      id: 'spot_5',
      name: 'Somnath Temple',
      category: 'Spiritual',
      latitude: 20.8880,
      longitude: 70.4012,
      entryFee: 0.0,
      distanceKm: 410.0,
      estimatedVisitDuration: const Duration(hours: 2),
      rating: 4.9,
      openingTime: '06:00 AM',
      closingTime: '09:00 PM',
    ),
  ];

  static final List<Hotel> hotels = [
    Hotel(
      id: 'hotel_1',
      name: 'Fern Sardar Sarovar Resort',
      address: 'Kevadia, near Statue of Unity',
      pricePerNight: 4500.0,
      latitude: 21.8400,
      longitude: 73.7150,
      rating: 4.6,
      distanceFromAttractionsKm: 2.5,
    ),
    Hotel(
      id: 'hotel_2',
      name: 'House of MG Heritage Hotel',
      address: 'Lal Darwaja, Ahmedabad',
      pricePerNight: 5200.0,
      latitude: 23.0250,
      longitude: 72.5810,
      rating: 4.8,
      distanceFromAttractionsKm: 1.2,
    ),
    Hotel(
      id: 'hotel_3',
      name: 'Woods at Sasan Gir Resort',
      address: 'Sasan Gir, Junagadh',
      pricePerNight: 6500.0,
      latitude: 21.1300,
      longitude: 70.8200,
      rating: 4.7,
      distanceFromAttractionsKm: 5.0,
    ),
  ];

  static final List<Restaurant> restaurants = [
    Restaurant(
      id: 'rest_1',
      name: 'Agashiye (Authentic Gujarati Thali)',
      cuisineType: 'Gujarati Heritage Thali',
      averageMealCost: 900.0,
      latitude: 23.0252,
      longitude: 72.5812,
      rating: 4.9,
      address: 'The House of MG, Lal Darwaja, Ahmedabad',
    ),
    Restaurant(
      id: 'rest_2',
      name: 'Vishalla Village Restaurant',
      cuisineType: 'Traditional Dining & Culture',
      averageMealCost: 750.0,
      latitude: 22.9980,
      longitude: 72.5350,
      rating: 4.5,
      address: 'Vasna Road, Opposite APMC Market, Ahmedabad',
    ),
    Restaurant(
      id: 'rest_3',
      name: 'Gordhan Thal',
      cuisineType: 'Unlimited Kathiyawadi Thali',
      averageMealCost: 450.0,
      latitude: 23.0300,
      longitude: 72.5100,
      rating: 4.6,
      address: 'SG Highway, Bodakdev, Ahmedabad',
    ),
  ];
}