// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiBZAMz1l6L0AZIBmzKy8G1XyaOm7DenA',
    appId: '1:560855009957:web:dea8a4507fc1e60258db4c',
    messagingSenderId: '560855009957',
    projectId: 'travelease-d9f90',
    authDomain: 'travelease-d9f90.firebaseapp.com',
    storageBucket: 'travelease-d9f90.firebasestorage.app',
    measurementId: 'G-DPQM68YT1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqCljaLRXKzyJiDZyrQQmUOzn1QR-peX4',
    appId: '1:560855009957:android:39c2ba355e2bd71458db4c',
    messagingSenderId: '560855009957',
    projectId: 'travelease-d9f90',
    storageBucket: 'travelease-d9f90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3AKqYhrciMJE9DCek9YZ7YFN94Z693PI',
    appId: '1:560855009957:ios:ad209cdb8747e22258db4c',
    messagingSenderId: '560855009957',
    projectId: 'travelease-d9f90',
    storageBucket: 'travelease-d9f90.firebasestorage.app',
    iosBundleId: 'com.example.travelPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3AKqYhrciMJE9DCek9YZ7YFN94Z693PI',
    appId: '1:560855009957:ios:ad209cdb8747e22258db4c',
    messagingSenderId: '560855009957',
    projectId: 'travelease-d9f90',
    storageBucket: 'travelease-d9f90.firebasestorage.app',
    iosBundleId: 'com.example.travelPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiBZAMz1l6L0AZIBmzKy8G1XyaOm7DenA',
    appId: '1:560855009957:web:0ef2dc18dda26b0558db4c',
    messagingSenderId: '560855009957',
    projectId: 'travelease-d9f90',
    authDomain: 'travelease-d9f90.firebaseapp.com',
    storageBucket: 'travelease-d9f90.firebasestorage.app',
    measurementId: 'G-0GC0P6YGWB',
  );
}
